- name: Build app for terraform
  hosts: localhost
  become: yes

  tasks:
  - name: install docker
    apt:
      name: docker.io
      state: present

  - name: build and push project
    docker_image:
      build:
        path: /tmp/App42PaaS-Java-MySQL
      name: aamitv/app1-terraform
      tag: latest
      push: yes
      source: build
