version: '3.8'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: aamitv/app-terraform
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile_db
     image: aamitv/db-terraform
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
